spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lab_task
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
jwt:
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
  api-docs:
    path: "/v3/api-docs"
logging:
  level:
    root: info
    org.springdoc: info
