spring:
  config:
    activate:
      on-profile: default,hateoas
  datasource:
    url: ${SQL_URL}
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
              - openid

      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
  api-docs:
    path: "/v3/api-docs"
logging:
  level:
    root: info
    org.springdoc: info

access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY}
  public: ${ACCESS_TOKEN_PUBLIC_KEY}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY}
  public: ${REFRESH_TOKEN_PUBLIC_KEY}

server:
  servlet:
    encoding:
      force: true