spring:
  config:
    activate:
      on-profile: hateoas
  datasource:
    url: jdbc:mysql://localhost:3306/lab_task
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
